### ISSUE TITLE
Route name contains <div> tags

### ISSUE THREAD

**Issue by JesseCrocker** [valhalla/lrm-valhalla#4]
This causes problems when using a custom display widget instead of the stock one.

**Comment by hanbyul-here** [comment]
It was left over from hack for our own example, thanks for issue! replaced tag to comma https://github.com/valhalla/lrm-valhalla/commit/a80a17a452a513c0e83d3c3cdc58acd9c02bf123#diff-0d2f3f8daf94e9d3078e3ec80470dd19R119
